### ISSUE TITLE
Add cut planes

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/jupyter_rs_vtk#20]
Add an API to allow users to add a cut plane for viewing cross-sections, and the UI to control them

**Comment by mkeilman** [comment]
See also [rslaser](https://github.com/radiasoft/rslaser/issues/34)

**Comment by robnagler** [comment]
relevant?

**Comment by mkeilman** [comment]
This was to support silas but was never used; closing (but I'll keep the branch locally)
